### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by donatiss** [larapack/voyager-hooks#10]
Hi,

after command 
`$ php artisan hook:install voyager-themes` I got a message 

>  [JsonSchema\Exception\ResourceNotFoundException]  file_get_contents(file://): failed to open stream: No such file or directory

Could You explain me, how to use Hooks?

**Comment by marktopper** [comment]
Can you please run this command with the `--verbose` flag?

**Comment by marktopper** [comment]
Closing due to missing feedback
