### ISSUE TITLE
Laravel tinker does not show prompt, works incorrectly

### ISSUE THREAD

**Issue by blitux** [larapack/voyager-hooks#15]
- Hooks Version: v1.0.4
- Voyager Version: 1.0.10
- Laravel Version: 5.5.28
- PHP Version: 7.1.12-3+ubuntu16.04.1+deb.sury.org+1

### Description:

After a clean install of laravel and larapack/voyager-hooks:v1.0.4, the command `php artisan tinker` does not show the prompt ">>>" and works incorrectly. Autocompletion doesn't work, arrow keys throws escape characters.

It seems like voyager-hooks is interfering with tinker or Psy Shell.

### Steps To Reproduce:

1. Install last version of laravel with `laravel new test`
2. Run `php artisan tinker`. You will see the prompt ">>>"
3. Run `composer require larapack/voyager-hooks:v1.0.4`
4. Run `php artisan tinker`. You will see Psy Shell's welcome message and NOT the prompt ">>>"

**Comment by marktopper** [comment]
Works perfectly for me using PHP v7.1.8.

Would you mind try again in a clean Laravel install?
Maybe this happens when used together with some other packages?

**Comment by blitux** [comment]
It seems the issue is solved now. It certainly happened before as I could reproduce it consistently using a clean laravel install, but now it's gone. Thank you @marktopper!
