### ISSUE TITLE
Voyager-hooks menu-item isn't visible and/or not working

### ISSUE THREAD

**Issue by FrankyJust** [larapack/voyager-hooks#24]
### Version information
Laravel 5.6.33
Voyager 1.1.9 (latest)
PHP 7.1.16
MySQL 5.7.21

### Details
After installation the menu-item isn't visible in Admin menu. When I go in the Menu Builder, the menu-item is visible. When I click on it, in 'Route for the menu item' the URL is voyager.hooks. When I add index to it, the menu-item is visible in Admin menu, but on clicking nothing happens.
I've installed after that voyager-polls, but this makes no difference.

**Comment by fletch3555** [comment]
Sounds like your user's role is just missing the `browse_hooks` permission.  Please confirm whether the permissions exists and is attached to the role.

**Comment by FrankyJust** [comment]
Thx. This was indeed the problem. This should been solved according the developer, but this seems not the case. And the documentation states nothing about this. Much more users did have in the past  problems with installation of hooks. By the way, also in several hook apps (i.e. Polls) there are problems. Developer isn't busy enough to maintain his code. From my point of view, this has a negative impact on Voyager itself.
