### ISSUE TITLE
Route [voyager.theme.index] not defined.

### ISSUE THREAD

**Issue by DerekBuntin** [larapack/voyager-hooks#28]
- Hooks Version: ^1.0
- Voyager Version: 1.1.10
- Laravel Version: 5.7.24
- PHP Version: >=7.1.3

### Description:

Themes and redirect hooks give the same error:

Route [voyager.theme.index] not defined.

### Steps To Reproduce: 

Try and access admin after logging in and the system gives a 500 error message.

NOTE:

Hooks Version: ^1.0
Voyager Version: 1.1
Laravel Version: 5.7.24
PHP Version: >=7.1.3

I have another project on the same local system running earlier versions of voyager and the two hook packages that work with Laravel 5.7.24.

UPDATE:

I updated the working project from Voyager 1.1 to 1.1.10 and this issue appeared.

**Comment by fletch3555** [comment]
This package does not provide any routes.  As I mentioned on the-control-group/voyager#3933, you should contact the creator of whatever hook you're using.  If it's broken, it's likely because it's using outdated functionality and/or has incorrect dependency version strings.

**Comment by DerekBuntin** [comment]
Thanks Eric, I've submitted this to devdojo instead, but it seems none of the hooks work as the redirect hook give the same problem.
