### ISSUE TITLE
[Feature Request] Hook creation documentation

### ISSUE THREAD

**Issue by victorpierredev** [larapack/voyager-hooks#5]
I would love to collaborate by creating and publishing hooks. I wonder if the documentation on how to create hooks is already in place.

**Comment by akazorg** [comment]
That is great Vitor! Let's build some hooks 👍 

We currently have a draft for the documentation, it requires some update.

There is also a pending issue with the setup process, @marktopper is currently working on that and soon will be concluded.

We are committed on shipping the Hooks system ASAP.

I'll keep you updated.
🚀

**Comment by marktopper** [comment]
I am working on some docs here: https://github.com/larapack/hook-docs
If you have any questions at all let me know.
