### ISSUE TITLE
After uninstall hook tables still in database

### ISSUE THREAD

**Issue by davodavodavo3** [larapack/voyager-hooks#8]
- Hooks Version: #.#.#
- Laravel Version: #.#.#
- PHP Version:

### Description:
After uninstall hook tables still in database. For example voyager-polls

**Comment by marktopper** [comment]
I will work on a fix for this.

**Comment by marktopper** [comment]
Closing this since hooks can now have migrations ran and rolled-back on install and uninstall after the release of https://github.com/larapack/hooks/pull/30

Let me know if you have this issue with a specific hook, then I will look into that hook for you.
